export enum APP_ROUTE {
  root = '/',
  auth = 'auth',
  login = 'login',
  forgotPassword = 'forgot-password',
  passwordResetLinkSent = 'password-reset-link-sent',
  createPassword = 'reset-password',
  dashboard = 'dashboard',
  transactions = 'transactions',
  expenses = 'expenses',
  incomes = 'incomes',
  balances = 'balances',
  budgets = 'budgets',
  profile = 'profile',
}
